-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Interface exposing (..)


type Actor
    = Actor


type Assignable
    = Assignable


type AuditEntry
    = AuditEntry


type Closable
    = Closable


type Comment
    = Comment


type Contribution
    = Contribution


type Deletable
    = Deletable


type EnterpriseAuditEntryData
    = EnterpriseAuditEntryData


type GitObject
    = GitObject


type GitSignature
    = GitSignature


type HovercardContext
    = HovercardContext


type Labelable
    = Labelable


type Lockable
    = Lockable


type MemberStatusable
    = MemberStatusable


type Minimizable
    = Minimizable


type Node
    = Node


type OauthApplicationAuditEntryData
    = OauthApplicationAuditEntryData


type OrganizationAuditEntryData
    = OrganizationAuditEntryData


type PackageOwner
    = PackageOwner


type ProfileOwner
    = ProfileOwner


type ProjectOwner
    = ProjectOwner


type Reactable
    = Reactable


type RepositoryAuditEntryData
    = RepositoryAuditEntryData


type RepositoryDiscussionAuthor
    = RepositoryDiscussionAuthor


type RepositoryDiscussionCommentAuthor
    = RepositoryDiscussionCommentAuthor


type RepositoryInfo
    = RepositoryInfo


type RepositoryNode
    = RepositoryNode


type RepositoryOwner
    = RepositoryOwner


type RequirableByPullRequest
    = RequirableByPullRequest


type Sponsorable
    = Sponsorable


type Starrable
    = Starrable


type Subscribable
    = Subscribable


type TeamAuditEntryData
    = TeamAuditEntryData


type TopicAuditEntryData
    = TopicAuditEntryData


type UniformResourceLocatable
    = UniformResourceLocatable


type Updatable
    = Updatable


type UpdatableComment
    = UpdatableComment


type Votable
    = Votable
