-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Github.Enum.SecurityAdvisoryEcosystem exposing (..)

import Json.Decode as Decode exposing (Decoder)


{-| The possible ecosystems of a security vulnerability's package.

  - Composer - PHP packages hosted at packagist.org
  - Go - Go modules
  - Maven - Java artifacts hosted at the Maven central repository
  - Npm - JavaScript packages hosted at npmjs.com
  - Nuget - .NET packages hosted at the NuGet Gallery
  - Pip - Python packages hosted at PyPI.org
  - Rubygems - Ruby gems hosted at RubyGems.org
  - Rust - Rust crates

-}
type SecurityAdvisoryEcosystem
    = Composer
    | Go
    | Maven
    | Npm
    | Nuget
    | Pip
    | Rubygems
    | Rust


list : List SecurityAdvisoryEcosystem
list =
    [ Composer, Go, Maven, Npm, Nuget, Pip, Rubygems, Rust ]


decoder : Decoder SecurityAdvisoryEcosystem
decoder =
    Decode.string
        |> Decode.andThen
            (\string ->
                case string of
                    "COMPOSER" ->
                        Decode.succeed Composer

                    "GO" ->
                        Decode.succeed Go

                    "MAVEN" ->
                        Decode.succeed Maven

                    "NPM" ->
                        Decode.succeed Npm

                    "NUGET" ->
                        Decode.succeed Nuget

                    "PIP" ->
                        Decode.succeed Pip

                    "RUBYGEMS" ->
                        Decode.succeed Rubygems

                    "RUST" ->
                        Decode.succeed Rust

                    _ ->
                        Decode.fail ("Invalid SecurityAdvisoryEcosystem type, " ++ string ++ " try re-running the @dillonkearns/elm-graphql CLI ")
            )


{-| Convert from the union type representing the Enum to a string that the GraphQL server will recognize.
-}
toString : SecurityAdvisoryEcosystem -> String
toString enum____ =
    case enum____ of
        Composer ->
            "COMPOSER"

        Go ->
            "GO"

        Maven ->
            "MAVEN"

        Npm ->
            "NPM"

        Nuget ->
            "NUGET"

        Pip ->
            "PIP"

        Rubygems ->
            "RUBYGEMS"

        Rust ->
            "RUST"


{-| Convert from a String representation to an elm representation enum.
This is the inverse of the Enum `toString` function. So you can call `toString` and then convert back `fromString` safely.

    Swapi.Enum.Episode.NewHope
        |> Swapi.Enum.Episode.toString
        |> Swapi.Enum.Episode.fromString
        == Just NewHope

This can be useful for generating Strings to use for <select> menus to check which item was selected.

-}
fromString : String -> Maybe SecurityAdvisoryEcosystem
fromString enumString____ =
    case enumString____ of
        "COMPOSER" ->
            Just Composer

        "GO" ->
            Just Go

        "MAVEN" ->
            Just Maven

        "NPM" ->
            Just Npm

        "NUGET" ->
            Just Nuget

        "PIP" ->
            Just Pip

        "RUBYGEMS" ->
            Just Rubygems

        "RUST" ->
            Just Rust

        _ ->
            Nothing
